# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  nero-nodejs-deploy
  namespace: default
  labels:
    app:  nero-nodejs-deploy
spec:
  selector:
    matchLabels:
      app: nero-nodejs-deploy
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  nero-nodejs-deploy
    spec:
      containers:
      - name:  nero-nodejs-deploy
        imagePullPolicy: Always
        image:  684348886286.dkr.ecr.eu-west-3.amazonaws.com/nero-repo:1.1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 256Mi
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_status/healthz
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        ports:
        - containerPort:  80
      restartPolicy: Always
---
